name: cookingrecipe
description: Cooking Recipie App.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  simple_animations: ^1.3.3
  hexcolor: ^1.0.2
  fluttertoast: ^4.0.1
  page_transition: ^1.1.5
  flutter_launcher_name: ^0.0.1
  share: ^0.6.4+2
  http: ^0.12.1
  shared_preferences: ^0.5.7+3
  rating_bar: ^0.2.0
  percent_indicator: ^2.1.3
  flutter_launcher_icons: ^0.7.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"

flutter_launcher_name:
  name: "Cooking Recipe"


flutter:

  uses-material-design: true

  assets:
    - assets/images/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

